apiVersion: v1
kind: Service
metadata:
  name: terraform-sidecar
  namespace: trendgetter
  labels:
    app: terraform-sidecar
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${TERRAFORM_SIDECAR_METALLB_IP}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: terraform-sidecar

